// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"
	"time"

	"github.com/concourse/concourse/atc"
	"github.com/concourse/concourse/atc/db"
)

type FakeWebhook struct {
	CreatedAtStub        func() time.Time
	createdAtMutex       sync.RWMutex
	createdAtArgsForCall []struct {
	}
	createdAtReturns struct {
		result1 time.Time
	}
	createdAtReturnsOnCall map[int]struct {
		result1 time.Time
	}
	IDStub        func() int
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
	}
	iDReturns struct {
		result1 int
	}
	iDReturnsOnCall map[int]struct {
		result1 int
	}
	MatcherStub        func() (*atc.WebhookMatcher, bool)
	matcherMutex       sync.RWMutex
	matcherArgsForCall []struct {
	}
	matcherReturns struct {
		result1 *atc.WebhookMatcher
		result2 bool
	}
	matcherReturnsOnCall map[int]struct {
		result1 *atc.WebhookMatcher
		result2 bool
	}
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	RulesStub        func() []atc.WebhookMatcherRule
	rulesMutex       sync.RWMutex
	rulesArgsForCall []struct {
	}
	rulesReturns struct {
		result1 []atc.WebhookMatcherRule
	}
	rulesReturnsOnCall map[int]struct {
		result1 []atc.WebhookMatcherRule
	}
	SecretStub        func() string
	secretMutex       sync.RWMutex
	secretArgsForCall []struct {
	}
	secretReturns struct {
		result1 string
	}
	secretReturnsOnCall map[int]struct {
		result1 string
	}
	SignatureAlgoStub        func() string
	signatureAlgoMutex       sync.RWMutex
	signatureAlgoArgsForCall []struct {
	}
	signatureAlgoReturns struct {
		result1 string
	}
	signatureAlgoReturnsOnCall map[int]struct {
		result1 string
	}
	SignatureHeaderStub        func() string
	signatureHeaderMutex       sync.RWMutex
	signatureHeaderArgsForCall []struct {
	}
	signatureHeaderReturns struct {
		result1 string
	}
	signatureHeaderReturnsOnCall map[int]struct {
		result1 string
	}
	TeamIDStub        func() int
	teamIDMutex       sync.RWMutex
	teamIDArgsForCall []struct {
	}
	teamIDReturns struct {
		result1 int
	}
	teamIDReturnsOnCall map[int]struct {
		result1 int
	}
	TokenStub        func() string
	tokenMutex       sync.RWMutex
	tokenArgsForCall []struct {
	}
	tokenReturns struct {
		result1 string
	}
	tokenReturnsOnCall map[int]struct {
		result1 string
	}
	TypeStub        func() string
	typeMutex       sync.RWMutex
	typeArgsForCall []struct {
	}
	typeReturns struct {
		result1 string
	}
	typeReturnsOnCall map[int]struct {
		result1 string
	}
	UpdatedAtStub        func() time.Time
	updatedAtMutex       sync.RWMutex
	updatedAtArgsForCall []struct {
	}
	updatedAtReturns struct {
		result1 time.Time
	}
	updatedAtReturnsOnCall map[int]struct {
		result1 time.Time
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWebhook) CreatedAt() time.Time {
	fake.createdAtMutex.Lock()
	ret, specificReturn := fake.createdAtReturnsOnCall[len(fake.createdAtArgsForCall)]
	fake.createdAtArgsForCall = append(fake.createdAtArgsForCall, struct {
	}{})
	stub := fake.CreatedAtStub
	fakeReturns := fake.createdAtReturns
	fake.recordInvocation("CreatedAt", []interface{}{})
	fake.createdAtMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) CreatedAtCallCount() int {
	fake.createdAtMutex.RLock()
	defer fake.createdAtMutex.RUnlock()
	return len(fake.createdAtArgsForCall)
}

func (fake *FakeWebhook) CreatedAtCalls(stub func() time.Time) {
	fake.createdAtMutex.Lock()
	defer fake.createdAtMutex.Unlock()
	fake.CreatedAtStub = stub
}

func (fake *FakeWebhook) CreatedAtReturns(result1 time.Time) {
	fake.createdAtMutex.Lock()
	defer fake.createdAtMutex.Unlock()
	fake.CreatedAtStub = nil
	fake.createdAtReturns = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeWebhook) CreatedAtReturnsOnCall(i int, result1 time.Time) {
	fake.createdAtMutex.Lock()
	defer fake.createdAtMutex.Unlock()
	fake.CreatedAtStub = nil
	if fake.createdAtReturnsOnCall == nil {
		fake.createdAtReturnsOnCall = make(map[int]struct {
			result1 time.Time
		})
	}
	fake.createdAtReturnsOnCall[i] = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeWebhook) ID() int {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
	}{})
	stub := fake.IDStub
	fakeReturns := fake.iDReturns
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *FakeWebhook) IDCalls(stub func() int) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *FakeWebhook) IDReturns(result1 int) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeWebhook) IDReturnsOnCall(i int, result1 int) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeWebhook) Matcher() (*atc.WebhookMatcher, bool) {
	fake.matcherMutex.Lock()
	ret, specificReturn := fake.matcherReturnsOnCall[len(fake.matcherArgsForCall)]
	fake.matcherArgsForCall = append(fake.matcherArgsForCall, struct {
	}{})
	stub := fake.MatcherStub
	fakeReturns := fake.matcherReturns
	fake.recordInvocation("Matcher", []interface{}{})
	fake.matcherMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeWebhook) MatcherCallCount() int {
	fake.matcherMutex.RLock()
	defer fake.matcherMutex.RUnlock()
	return len(fake.matcherArgsForCall)
}

func (fake *FakeWebhook) MatcherCalls(stub func() (*atc.WebhookMatcher, bool)) {
	fake.matcherMutex.Lock()
	defer fake.matcherMutex.Unlock()
	fake.MatcherStub = stub
}

func (fake *FakeWebhook) MatcherReturns(result1 *atc.WebhookMatcher, result2 bool) {
	fake.matcherMutex.Lock()
	defer fake.matcherMutex.Unlock()
	fake.MatcherStub = nil
	fake.matcherReturns = struct {
		result1 *atc.WebhookMatcher
		result2 bool
	}{result1, result2}
}

func (fake *FakeWebhook) MatcherReturnsOnCall(i int, result1 *atc.WebhookMatcher, result2 bool) {
	fake.matcherMutex.Lock()
	defer fake.matcherMutex.Unlock()
	fake.MatcherStub = nil
	if fake.matcherReturnsOnCall == nil {
		fake.matcherReturnsOnCall = make(map[int]struct {
			result1 *atc.WebhookMatcher
			result2 bool
		})
	}
	fake.matcherReturnsOnCall[i] = struct {
		result1 *atc.WebhookMatcher
		result2 bool
	}{result1, result2}
}

func (fake *FakeWebhook) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeWebhook) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakeWebhook) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) Rules() []atc.WebhookMatcherRule {
	fake.rulesMutex.Lock()
	ret, specificReturn := fake.rulesReturnsOnCall[len(fake.rulesArgsForCall)]
	fake.rulesArgsForCall = append(fake.rulesArgsForCall, struct {
	}{})
	stub := fake.RulesStub
	fakeReturns := fake.rulesReturns
	fake.recordInvocation("Rules", []interface{}{})
	fake.rulesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) RulesCallCount() int {
	fake.rulesMutex.RLock()
	defer fake.rulesMutex.RUnlock()
	return len(fake.rulesArgsForCall)
}

func (fake *FakeWebhook) RulesCalls(stub func() []atc.WebhookMatcherRule) {
	fake.rulesMutex.Lock()
	defer fake.rulesMutex.Unlock()
	fake.RulesStub = stub
}

func (fake *FakeWebhook) RulesReturns(result1 []atc.WebhookMatcherRule) {
	fake.rulesMutex.Lock()
	defer fake.rulesMutex.Unlock()
	fake.RulesStub = nil
	fake.rulesReturns = struct {
		result1 []atc.WebhookMatcherRule
	}{result1}
}

func (fake *FakeWebhook) RulesReturnsOnCall(i int, result1 []atc.WebhookMatcherRule) {
	fake.rulesMutex.Lock()
	defer fake.rulesMutex.Unlock()
	fake.RulesStub = nil
	if fake.rulesReturnsOnCall == nil {
		fake.rulesReturnsOnCall = make(map[int]struct {
			result1 []atc.WebhookMatcherRule
		})
	}
	fake.rulesReturnsOnCall[i] = struct {
		result1 []atc.WebhookMatcherRule
	}{result1}
}

func (fake *FakeWebhook) Secret() string {
	fake.secretMutex.Lock()
	ret, specificReturn := fake.secretReturnsOnCall[len(fake.secretArgsForCall)]
	fake.secretArgsForCall = append(fake.secretArgsForCall, struct {
	}{})
	stub := fake.SecretStub
	fakeReturns := fake.secretReturns
	fake.recordInvocation("Secret", []interface{}{})
	fake.secretMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) SecretCallCount() int {
	fake.secretMutex.RLock()
	defer fake.secretMutex.RUnlock()
	return len(fake.secretArgsForCall)
}

func (fake *FakeWebhook) SecretCalls(stub func() string) {
	fake.secretMutex.Lock()
	defer fake.secretMutex.Unlock()
	fake.SecretStub = stub
}

func (fake *FakeWebhook) SecretReturns(result1 string) {
	fake.secretMutex.Lock()
	defer fake.secretMutex.Unlock()
	fake.SecretStub = nil
	fake.secretReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) SecretReturnsOnCall(i int, result1 string) {
	fake.secretMutex.Lock()
	defer fake.secretMutex.Unlock()
	fake.SecretStub = nil
	if fake.secretReturnsOnCall == nil {
		fake.secretReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.secretReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) SignatureAlgo() string {
	fake.signatureAlgoMutex.Lock()
	ret, specificReturn := fake.signatureAlgoReturnsOnCall[len(fake.signatureAlgoArgsForCall)]
	fake.signatureAlgoArgsForCall = append(fake.signatureAlgoArgsForCall, struct {
	}{})
	stub := fake.SignatureAlgoStub
	fakeReturns := fake.signatureAlgoReturns
	fake.recordInvocation("SignatureAlgo", []interface{}{})
	fake.signatureAlgoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) SignatureAlgoCallCount() int {
	fake.signatureAlgoMutex.RLock()
	defer fake.signatureAlgoMutex.RUnlock()
	return len(fake.signatureAlgoArgsForCall)
}

func (fake *FakeWebhook) SignatureAlgoCalls(stub func() string) {
	fake.signatureAlgoMutex.Lock()
	defer fake.signatureAlgoMutex.Unlock()
	fake.SignatureAlgoStub = stub
}

func (fake *FakeWebhook) SignatureAlgoReturns(result1 string) {
	fake.signatureAlgoMutex.Lock()
	defer fake.signatureAlgoMutex.Unlock()
	fake.SignatureAlgoStub = nil
	fake.signatureAlgoReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) SignatureAlgoReturnsOnCall(i int, result1 string) {
	fake.signatureAlgoMutex.Lock()
	defer fake.signatureAlgoMutex.Unlock()
	fake.SignatureAlgoStub = nil
	if fake.signatureAlgoReturnsOnCall == nil {
		fake.signatureAlgoReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.signatureAlgoReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) SignatureHeader() string {
	fake.signatureHeaderMutex.Lock()
	ret, specificReturn := fake.signatureHeaderReturnsOnCall[len(fake.signatureHeaderArgsForCall)]
	fake.signatureHeaderArgsForCall = append(fake.signatureHeaderArgsForCall, struct {
	}{})
	stub := fake.SignatureHeaderStub
	fakeReturns := fake.signatureHeaderReturns
	fake.recordInvocation("SignatureHeader", []interface{}{})
	fake.signatureHeaderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) SignatureHeaderCallCount() int {
	fake.signatureHeaderMutex.RLock()
	defer fake.signatureHeaderMutex.RUnlock()
	return len(fake.signatureHeaderArgsForCall)
}

func (fake *FakeWebhook) SignatureHeaderCalls(stub func() string) {
	fake.signatureHeaderMutex.Lock()
	defer fake.signatureHeaderMutex.Unlock()
	fake.SignatureHeaderStub = stub
}

func (fake *FakeWebhook) SignatureHeaderReturns(result1 string) {
	fake.signatureHeaderMutex.Lock()
	defer fake.signatureHeaderMutex.Unlock()
	fake.SignatureHeaderStub = nil
	fake.signatureHeaderReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) SignatureHeaderReturnsOnCall(i int, result1 string) {
	fake.signatureHeaderMutex.Lock()
	defer fake.signatureHeaderMutex.Unlock()
	fake.SignatureHeaderStub = nil
	if fake.signatureHeaderReturnsOnCall == nil {
		fake.signatureHeaderReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.signatureHeaderReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) TeamID() int {
	fake.teamIDMutex.Lock()
	ret, specificReturn := fake.teamIDReturnsOnCall[len(fake.teamIDArgsForCall)]
	fake.teamIDArgsForCall = append(fake.teamIDArgsForCall, struct {
	}{})
	stub := fake.TeamIDStub
	fakeReturns := fake.teamIDReturns
	fake.recordInvocation("TeamID", []interface{}{})
	fake.teamIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) TeamIDCallCount() int {
	fake.teamIDMutex.RLock()
	defer fake.teamIDMutex.RUnlock()
	return len(fake.teamIDArgsForCall)
}

func (fake *FakeWebhook) TeamIDCalls(stub func() int) {
	fake.teamIDMutex.Lock()
	defer fake.teamIDMutex.Unlock()
	fake.TeamIDStub = stub
}

func (fake *FakeWebhook) TeamIDReturns(result1 int) {
	fake.teamIDMutex.Lock()
	defer fake.teamIDMutex.Unlock()
	fake.TeamIDStub = nil
	fake.teamIDReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeWebhook) TeamIDReturnsOnCall(i int, result1 int) {
	fake.teamIDMutex.Lock()
	defer fake.teamIDMutex.Unlock()
	fake.TeamIDStub = nil
	if fake.teamIDReturnsOnCall == nil {
		fake.teamIDReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.teamIDReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeWebhook) Token() string {
	fake.tokenMutex.Lock()
	ret, specificReturn := fake.tokenReturnsOnCall[len(fake.tokenArgsForCall)]
	fake.tokenArgsForCall = append(fake.tokenArgsForCall, struct {
	}{})
	stub := fake.TokenStub
	fakeReturns := fake.tokenReturns
	fake.recordInvocation("Token", []interface{}{})
	fake.tokenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) TokenCallCount() int {
	fake.tokenMutex.RLock()
	defer fake.tokenMutex.RUnlock()
	return len(fake.tokenArgsForCall)
}

func (fake *FakeWebhook) TokenCalls(stub func() string) {
	fake.tokenMutex.Lock()
	defer fake.tokenMutex.Unlock()
	fake.TokenStub = stub
}

func (fake *FakeWebhook) TokenReturns(result1 string) {
	fake.tokenMutex.Lock()
	defer fake.tokenMutex.Unlock()
	fake.TokenStub = nil
	fake.tokenReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) TokenReturnsOnCall(i int, result1 string) {
	fake.tokenMutex.Lock()
	defer fake.tokenMutex.Unlock()
	fake.TokenStub = nil
	if fake.tokenReturnsOnCall == nil {
		fake.tokenReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.tokenReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) Type() string {
	fake.typeMutex.Lock()
	ret, specificReturn := fake.typeReturnsOnCall[len(fake.typeArgsForCall)]
	fake.typeArgsForCall = append(fake.typeArgsForCall, struct {
	}{})
	stub := fake.TypeStub
	fakeReturns := fake.typeReturns
	fake.recordInvocation("Type", []interface{}{})
	fake.typeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) TypeCallCount() int {
	fake.typeMutex.RLock()
	defer fake.typeMutex.RUnlock()
	return len(fake.typeArgsForCall)
}

func (fake *FakeWebhook) TypeCalls(stub func() string) {
	fake.typeMutex.Lock()
	defer fake.typeMutex.Unlock()
	fake.TypeStub = stub
}

func (fake *FakeWebhook) TypeReturns(result1 string) {
	fake.typeMutex.Lock()
	defer fake.typeMutex.Unlock()
	fake.TypeStub = nil
	fake.typeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) TypeReturnsOnCall(i int, result1 string) {
	fake.typeMutex.Lock()
	defer fake.typeMutex.Unlock()
	fake.TypeStub = nil
	if fake.typeReturnsOnCall == nil {
		fake.typeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.typeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeWebhook) UpdatedAt() time.Time {
	fake.updatedAtMutex.Lock()
	ret, specificReturn := fake.updatedAtReturnsOnCall[len(fake.updatedAtArgsForCall)]
	fake.updatedAtArgsForCall = append(fake.updatedAtArgsForCall, struct {
	}{})
	stub := fake.UpdatedAtStub
	fakeReturns := fake.updatedAtReturns
	fake.recordInvocation("UpdatedAt", []interface{}{})
	fake.updatedAtMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWebhook) UpdatedAtCallCount() int {
	fake.updatedAtMutex.RLock()
	defer fake.updatedAtMutex.RUnlock()
	return len(fake.updatedAtArgsForCall)
}

func (fake *FakeWebhook) UpdatedAtCalls(stub func() time.Time) {
	fake.updatedAtMutex.Lock()
	defer fake.updatedAtMutex.Unlock()
	fake.UpdatedAtStub = stub
}

func (fake *FakeWebhook) UpdatedAtReturns(result1 time.Time) {
	fake.updatedAtMutex.Lock()
	defer fake.updatedAtMutex.Unlock()
	fake.UpdatedAtStub = nil
	fake.updatedAtReturns = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeWebhook) UpdatedAtReturnsOnCall(i int, result1 time.Time) {
	fake.updatedAtMutex.Lock()
	defer fake.updatedAtMutex.Unlock()
	fake.UpdatedAtStub = nil
	if fake.updatedAtReturnsOnCall == nil {
		fake.updatedAtReturnsOnCall = make(map[int]struct {
			result1 time.Time
		})
	}
	fake.updatedAtReturnsOnCall[i] = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeWebhook) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWebhook) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.Webhook = new(FakeWebhook)
